### ISSUE TITLE
wiki : /journey

### ISSUE THREAD

**Issue by bsisic** [TfLlu/TfL-API#22]
'Not Found' on /Journey/{from}/to/{to}
false url in example
work with -> https://dev.tfl.lu/dev/Journey/49.59744,6.14077/to/49.542,6.19942

**Comment by Kaweechelchen** [comment]
whoops...copy paste error

fixed on wiki

thanks

**Comment by bsisic** [comment]
np !
and for StopPoint/{id} when we call this endpoint with '200901011' like your example that's return an empty array but '200901011' exist ...

**Comment by Kaweechelchen** [comment]
off topic, mais oui

le truc est que leur API est sur le cul...
http://travelplanner.mobiliteit.lu/restproxy/departureBoard?accessId=cdt&format=json&id=A=1@L=200901011

ou encore: http://travelplanner.mobiliteit.lu/restproxy/departureBoard?accessId=cdt&id=A=1@O=Belair,%20Sacr%C3%A9-Coeur@X=6,113204@Y=49,610279@U=82@L=200403005@B=1@p=1459856195&format=json

cf: https://data.public.lu/en/datasets/arrets-de-transport-public-et-departs-en-temps-reel/

**Comment by Kaweechelchen** [comment]
https://twitter.com/faq/status/816224289535967232

**Comment by bsisic** [comment]
sorry !

ahah pas de soucis merci à toi faut pas trop les pousser ;)

**Comment by Kaweechelchen** [comment]
On va ajouter des checks pour ceci: #23
