### ISSUE TITLE
Search Bikepoint irrelevant search results

### ISSUE THREAD

**Issue by petzlux** [TfLlu/TfL-API#24]
For search query `Schlass` contains irrelevant results ?

https://dev.tfl.lu/dev/BikePoint/Search/schlass

**Comment by Kaweechelchen** [comment]
We can disable fuzzy search, but then you need to enter special characters for "Belair, Sacré-Coeur" for example...

**Comment by petzlux** [comment]
Okay not critical at the moment, as a relevant result is returned first!

**Comment by pukkatea** [comment]
as said before this is fuzzy search, and was much appreciated by some teams @ Game of code, hence keeping it this way
