### ISSUE TITLE
Documentation for Journey endpoint ? 

### ISSUE THREAD

**Issue by petzlux** [TfLlu/TfL-API#26]
Altough most endpoint results are pretty self explanatory, the `Journey` one is more complex and would benefit from a documentation of its output. 

https://dev.tfl.lu/dev/Journey/49.59744,6.14077/to/49.542,6.19942

**Comment by Kaweechelchen** [comment]
Never found any information about a documentation on opentripplanner myself, but here's the answer from openOV, which we proxy: https://twitter.com/openOV/status/782926387208486912

**Comment by Kaweechelchen** [comment]
http://dev.opentripplanner.org/apidoc/1.0.0/resource_PlannerResource.html
